version: '3'
services:
  mongodb-dev:
    image: mongo:latest
    ports:
      - 27017:27017
  me:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb-dev"
    ports:
      - 8081:8081
    depends_on:
      - mongodb-dev
